# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: '#z-section'
    weight: 10
  - name: 定位
    url: '#nrlab-overview'
    weight: 20
  - name: 研究方向
    url: '#research-directions'
    weight: 30
  - name: 团队基础
    url: '#team-foundation'
    weight: 40
  - name: 发表文章
    url: '#publications'
    weight: 45
  - name: 传播矩阵
    url: '#outreach-matrix'
    weight: 50
  - name: 训练招募
    url: '#training-recruitment'
    weight: 60
  - name: 联系
    url: '#contact'
    weight: 70
  - name: 申请
    url: 'https://hlab2023.wjx.cn/vm/rnTipUj.aspx'
    weight: 80
