# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#z-section'
    weight: 10
  - name: Focus
    url: '#nrlab-overview'
    weight: 20
  - name: Research
    url: '#research-directions'
    weight: 30
  - name: Team
    url: '#team-foundation'
    weight: 40
  - name: Publications
    url: '#publications'
    weight: 45
  - name: Outreach
    url: '#outreach-matrix'
    weight: 50
  - name: Join
    url: '#training-recruitment'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
  - name: Apply
    url: 'https://hlab2023.wjx.cn/vm/rnTipUj.aspx'
    weight: 80
  - name: Visitors
    url: '#visitor-countries'
    weight: 90
